---
abstract: 'a TT2 Template exporter'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Exporter-Template
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: '> 0.8006'
  Moo: '> 1.004'
  Template: 2.22
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-Exporter-Template/issues
  homepage: https://github.com/LibreCat/Catmandu-Exporter-Template
  repository: https://github.com/LibreCat/Catmandu-Exporter-Template.git
version: v0.01
x_contributors:
  - 'vpeil <vitali.peil@uni-bielefeld.de>'
